# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# Solicita ao usuário dois números inteiros
numero1 = int(input("Digite o primeiro número inteiro: "))
numero2 = int(input("Digite o segundo número inteiro: "))

# Processamento: realiza as operações
soma = numero1 + numero2
produto = numero1 * numero2
diferenca = numero1 - numero2

# Tratamento para evitar divisão por zero
if numero2 != 0:
    quociente = numero1 / numero2
else:
    quociente = "Indefinido (divisão por zero)"

# Saída: exibe os resultados
print("\n--- Resultados ---")
print(f"Soma: {soma}")
print(f"Produto: {produto}")
print(f"Diferença: {diferenca}")
print(f"Quociente: {quociente}")