# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# Imprime o cabeçalho da tabela
print("Número  Quadrado  Cubo")

# Calcula e imprime os valores de 0 a 10
for numero in range(0, 11):
    quadrado = numero ** 2
    cubo = numero ** 3
    print(f"{numero:<7} {quadrado:<9} {cubo}")