# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# Solicita os dados do usuário
peso = float(input("Digite seu peso em kg: "))
altura = float(input("Digite sua altura em metros: "))

# Calcula o IMC
imc = peso / (altura ** 2)

# Exibe o resultado do IMC
print(f"Seu IMC é: {imc:.2f}")

# Interpretação do IMC
if imc < 18.5:
    print("Classificação: Abaixo do peso")
elif 18.5 <= imc < 25:
    print("Classificação: Peso normal")
elif 25 <= imc < 30:
    print("Classificação: Sobrepeso")
elif 30 <= imc < 35:
    print("Classificação: Obesidade grau I")
elif 35 <= imc < 40:
    print("Classificação: Obesidade grau II")
else:
    print("Classificação: Obesidade grau III (mórbida)")