# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# População mundial atual (2025)
populacao_atual = 8225409613

# Taxa de crescimento anual (0,836%)
taxa_crescimento = 0.00836

print("Estimativa de crescimento populacional mundial:")
print(f"População atual: {populacao_atual:,}")

# Calcula e exibe a população estimada para os próximos 5 anos
for ano in range(1, 6):
    populacao_estimada = populacao_atual * ((1 + taxa_crescimento) ** ano)
    print(f"Ano {ano}: {int(populacao_estimada):,}")