# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# Solicita ao usuário o raio do círculo
raio = int(input("Digite o raio do círculo: "))

# Define o valor de pi
pi = 3.14159

# Calcula as medidas
diametro = 2 * raio
circunferencia = 2 * pi * raio
area = pi * raio * raio

# Exibe os resultados
print(f"Diâmetro: {diametro}")
print(f"Circunferência: {circunferencia}")
print(f"Área: {area}")