# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXv6yUE5wRgfeUxMnh2dBmtOpV-6qY7v
"""

# Solicita ao usuário um número de 5 dígitos
numero = int(input("Digite um número de 5 dígitos: "))

# Verifica se o número tem exatamente 5 dígitos
if 10000 <= numero <= 99999:
    # Separa os dígitos usando divisão inteira e resto da divisão (módulo)
    digito1 = numero // 10000
    digito2 = (numero % 10000) // 1000
    digito3 = (numero % 1000) // 100
    digito4 = (numero % 100) // 10
    digito5 = numero % 10

    # Exibe os dígitos separados por três espaços
    print(digito1, digito2, digito3, digito4, digito5, sep="   ")

else:
    print("Número inválido! Por favor, digite um número com 5 dígitos.")